services:
  - type: web
    name: iwanyu-backend
    env: node
    region: ohio
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
    autoDeploy: true
    branch: main
    rootDir: backend
